import { Prisma } from '@prisma/client';

export interface CreateAuditLogInput {
  actorUserId?: string;
  actorDeviceId?: string;
  actorUserRole?: string;

  action: string;
  entityType: string;
  entityId?: string;

  success?: boolean;

  ipAddress?: string;
  userAgent?: string;

  metadata?: Prisma.InputJsonValue;
}

export const AuditAction = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_REGISTER: 'AUTH_REGISTER',

  ADVERTISER_CREATED: 'ADVERTISER_CREATED',
  ADVERTISER_REGISTERED: 'ADVERTISER_REGISTERED',
  ADVERTISER_UPDATED: 'ADVERTISER_UPDATED',
  ADVERTISER_DELETED: 'ADVERTISER_DELETED',

  CAMPAIGN_CREATED: 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED: 'CAMPAIGN_UPDATED',
  CAMPAIGN_CREATIVE_UPDATED: 'CAMPAIGN_CREATIVE_UPDATED',
  CAMPAIGN_ACTIVATED: 'CAMPAIGN_ACTIVATED',
  CAMPAIGN_CANCELLED: 'CAMPAIGN_CANCELLED',
  CAMPAIGN_COMPLETED: 'CAMPAIGN_COMPLETED',
  CAMPAIGN_DELETED: 'CAMPAIGN_DELETED',

  MEDIA_UPLOADED: 'MEDIA_UPLOADED',
  MEDIA_DELETED: 'MEDIA_DELETED',

  DEVICE_CREATED: 'DEVICE_CREATED',
  DEVICE_UPDATED: 'DEVICE_UPDATED',
  DEVICE_DELETED: 'DEVICE_DELETED',

  DEVICE_PROVISIONING_CREATED: 'DEVICE_PROVISIONING_CREATED',
  DEVICE_PROVISIONED: 'DEVICE_PROVISIONED',

  DRIVER_CREATED: 'DRIVER_CREATED',
  DRIVER_REGISTERED: 'DRIVER_REGISTERED',
  DRIVER_UPDATED: 'DRIVER_UPDATED',
  DRIVER_DELETED: 'DRIVER_DELETED',

  DRIVER_DOCUMENT_CREATED: 'DRIVER_DOCUMENT_CREATED',
  DRIVER_DOCUMENT_VERIFIED: 'DRIVER_DOCUMENT_VERIFIED',
  DRIVER_DOCUMENT_UPDATED: 'DRIVER_DOCUMENT_UPDATED',
  DRIVER_DOCUMENT_DELETED: 'DRIVER_DOCUMENT_DELETED',

  RICKSHAW_CREATED: 'RICKSHAW_CREATED',
  RICKSHAW_UPDATED: 'RICKSHAW_UPDATED',
  RICKSHAW_DELETED: 'RICKSHAW_DELETED',

  PLAYLIST_CREATED: 'PLAYLIST_CREATED',
  PLAYLIST_UPDATED: 'PLAYLIST_UPDATED',
  PLAYLIST_PUBLISHED: 'PLAYLIST_PUBLISHED',

  DEPLOYMENT_CREATED: 'DEPLOYMENT_CREATED',
  DEPLOYMENT_UPDATED: 'DEPLOYMENT_UPDATED',

  PAYOUT_GENERATED: 'PAYOUT_GENERATED',
  PAYOUT_MARKED_PAID: 'PAYOUT_MARKED_PAID',
  PAYOUT_DELETED: 'PAYOUT_DELETED',
} as const;
