export const DRIVER_ACTIVE_DAY_THRESHOLD = 8;
export const SHIFT_BREAK_THRESHOLD_MINUTES = 30;
export const HEARTBEAT_INTERVAL_MINUTES = 5;
export const DRIVER_PAYOUT = {
  MONTHLY_INCENTIVE: 1000,

  EXPECTED_ACTIVE_DAYS: 25,
};