export const PLAYER_RUNTIME = {
  SYNC_INTERVAL_SECONDS: 300,          // 5 min

  HEARTBEAT_INTERVAL_SECONDS: 60,      // 1 min

  TELEMETRY_INTERVAL_SECONDS: 300,     // 5 min

  DOWNLOAD_RETRY_INTERVAL_SECONDS: 30,

  MIN_BATTERY_FOR_SYNC: 15,
} as const;